### ISSUE TITLE
how to register the dataset?

### ISSUE THREAD

**Issue by lenlea** [ucbdrive/few-shot-object-detection#1]
KeyError: "Dataset 'voc_2007_trainval_base1' is not registered!

**Comment by aeinsara** [comment]
I have the same problem! Did you solve it?

**Comment by 2006pmach** [comment]
Same

**Comment by yashika-git** [comment]
@lenlea, @aeinsara, @2006pmach, Could anyone of you solve this problem?
If yes, please let me know how to resolve this.
Thanks

**Comment by RoxanaAz** [comment]
same problem
any idea?
