### ISSUE TITLE
about error fsdet

### ISSUE THREAD

**Issue by dmuqlzhang** [ucbdrive/few-shot-object-detection#10]
![image](https://user-images.githubusercontent.com/47552281/78755488-d483d700-79ab-11ea-93fe-e9b702725585.png)
 I according to your config， but got the error like above， can you help me what‘s wrong？

**Comment by xinw1012** [comment]
It looks like a version miss-matching issue to me. Do you have previously installed PyTorch with a different CUDA version you used to build `fsdet`?  You may build `fsdet` and install other dependencies in a clean virtual environment?  

Hope this helps.

**Comment by shivamsaboo17** [comment]
```
/anaconda3/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:262:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^
error: command 'gcc' failed with exit status 1
```

Getting this error while building fsdet.
My config:
cuda ver: 10.2
python: 3.7
gcc ver: 5.4.0

**Comment by shivamsaboo17** [comment]
Fixed this by using older version of detectron==0.1 (0.1.2 relased very recently gives this error) and pytorch==1.4 and torchvision==0.5.

**Comment by xinw1012** [comment]
Thanks for the clarification @shivamsaboo17 We didn't realize the recent detectron2 release breaks gives the error here.  But if you are using the entire codebase we provided here, you don't need to download the detectron2 from the official website anymore. You can just build the fsdet following the instructions.

**Comment by jd730** [comment]
Hi @xinw1012, I think this error occurred not because of the version of installed detectron2 but PyTorch version,>=1.5, or torchvision>=0.6. If I remember correctly, old detectron2 also causes same error.
