### ISSUE TITLE
FloatingPointError

### ISSUE THREAD

**Issue by jinweiLiu** [ucbdrive/few-shot-object-detection#104]
Hello! When I start training, the following issue occurred “FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged.” What should I do?

**Comment by diaosilei** [comment]
Hello! Have you solved your problem?

**Comment by Zll99** [comment]
> Hello! When I start training, the following issue occurred “FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged.” What should I do?

Hello! Have you solved your problem?

**Comment by jinweiLiu** [comment]
decrease the learning rate may help

**Comment by Zll99** [comment]
> decrease the learning rate may help

I've tried this method, but it didn't solve my problem. Although, thank you for your reply.

**Comment by diaosilei** [comment]
> decrease the learning rate may help

I finally solve the problem by decreasing the learning rate to 0.0000000000000001. Why is the rate so small？

**Comment by jgsimard** [comment]
@diaosilei , @jinweiLiu did you solve the problem ? I get the the same thing! The training starts but it diverges, even if I decrease the learning rate

**Comment by xinw1012** [comment]
Hi,

sorry for replying to the thread late.  Could you let me know what your
setup is? Like your Pytorch, detectron2, and cudnn version?  The code was
tested in Pytorch 1.6 and Detectron2 v0.2.1.   Maybe you can check whether
the problem can be resolved if an older version is used?

Also, if you have any additional information to share to resolve the issue,
please let us know. We will look into the issue on our end as well.

Thanks,
Xin

**Comment by jinweiLiu** [comment]
you could try to set the learning rate lower发自我的荣耀手机-------- 原始邮件 --------发件人： jgsimard ***@***.***>日期： 2021年4月14日周三 11:36收件人： ucbdrive/few-shot-object-detection ***@***.***>抄送： jinweiLiu ***@***.***>, Mention ***@***.***>主    题： Re: [ucbdrive/few-shot-object-detection] FloatingPointError (#104)
@diaosilei , @jinweiLiu did you solve the problem ? I get the the same thing! The training starts but it diverges, even if I decrease the learning rate

**Comment by jgsimard** [comment]
Hi, I think it it a mismatch with detectron v.04. It works well with
 detectron v0.3 !

**Comment by xinw1012** [comment]
Great news! @thomasehuang and I would also keep an eye on updating the codebase to the latest detectron2. It's a bit unfortunate that sometimes these library versions are not completely backward compatible.
