### ISSUE TITLE
Get zero ap for all classes after finetuning stage

### ISSUE THREAD

**Issue by tymanman** [ucbdrive/few-shot-object-detection#111]
I follow the guidance to pretrain a base model for 15 base classes and convert the model by random initialization, finally I finetune the model on all classes.However the ap of all classes is zero, neither the auto evaluation at the end of training nor a repeated evaluation by the script of tool_test.How come?

**Comment by xinw1012** [comment]
Hey sorry for the delayed response.  Would you like to provide us a bit more details about your training procedure and configs/logs for a closer inspection? 

Thanks!

**Comment by tymanman** [comment]
There was a mistake I made when loading the pretrained model.Thank u.



发自我的iPhone


------------------ Original ------------------
From: Xin Wang ***@***.***&gt;
Date: Fri,May 14,2021 10:34 AM
To: ucbdrive/few-shot-object-detection ***@***.***&gt;
Cc: tymanman ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ucbdrive/few-shot-object-detection] Get zero ap for all classes after finetuning stage (#111)





 
Hey sorry for the delayed response.  Would you like to provide us a bit more details about your training procedure and configs/logs for a closer inspection?
 
Thanks!
