### ISSUE TITLE
COCO datasets: test the model you provide ,but the AP is only 5.002

### ISSUE THREAD

**Issue by xiaoliqiangxxqzz** [ucbdrive/few-shot-object-detection#115]
When I used the 10shot model you trained on the Coco, I found that the AP was only 5.002 
![1620733393(1)](https://user-images.githubusercontent.com/20881108/117810023-7782e080-b291-11eb-9360-68bbb5ca00f1.png)

Is there anything I should pay attention to?

**Comment by scott-vsi** [comment]
Which model/config are you running? That is very similar to the results [reported](https://github.com/ucbdrive/few-shot-object-detection/blob/master/docs/MODEL_ZOO.md#10-shot-3), at least for the FRCN+ft-full model: 

name | nAP
----- | ---
FRCN+ft-full | 5.5
TFA w/ fc | 9.1
TFA w/ cos | 9.1

**Comment by SmallsmallRain** [comment]
> Which model/config are you running? That is very similar to the results [reported](https://github.com/ucbdrive/few-shot-object-detection/blob/master/docs/MODEL_ZOO.md#10-shot-3), at least for the FRCN+ft-full model:
> 
> name	AP
> FRCN+ft-full	5.5
> TFA w/ fc	9.1
> TFA w/ cos	9.1
I used the model with cos classifier of the 10 shot , and the models and data used are all provided by them.

**Comment by xiaoliqiangxxqzz** [comment]
> Which model/config are you running? That is very similar to the results [reported](https://github.com/ucbdrive/few-shot-object-detection/blob/master/docs/MODEL_ZOO.md#10-shot-3), at least for the FRCN+ft-full model:
> 
> name	AP
> FRCN+ft-full	5.5
> TFA w/ fc	9.1
> TFA w/ cos	9.1

I use the model with cos classifier of 10 shot, and the models and data used are all provided by them.

**Comment by xinw1012** [comment]
Hi, thanks for your interest in our work.  Just to confirm, did you try to download the models from the model zoo directly? https://github.com/ucbdrive/few-shot-object-detection/blob/master/docs/MODEL_ZOO.md#10-shot-3?  Can you verify the evaluation setups? We also released the training/eval logs in `metrics` so you may use it as an indicator for any discrepancy.  There should not be a difference if you were using the pre-trained models.  You can keep updating us if you have additional information on your experiment setups. 

Thanks!
