### ISSUE TITLE
VOC datasets: train all instances of novel classes

### ISSUE THREAD

**Issue by cats0212** [ucbdrive/few-shot-object-detection#116]
I  want to train all the instances of novel classes. 
For example airplane have 916 instances, can I directly modify _box_1shot_aeroplane_train.txt_ to write 916 image paths to it? Then run 

python3-m tools.train_net --num-gpus 8 \
--config-file configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_ft_novel1_1shot.yaml \
Opts model.weights checkpoints/ VOC/FASTER_RCNN/FASTER_RCNN_R_101_FPN_ALL1 /model_reset_remove.pth

Is the training one instance of airplane or 916 instances of airplane?

thanks.

**Comment by thomasehuang** [comment]
Apologies for the late response. I believe that should work, as the code will load in all the images in the specified .txt file. You can try it and let me know if that works.

Will close for now. Please feel free to reopen if it is still an issue.
