### ISSUE TITLE
Configuration files are so confusing

### ISSUE THREAD

**Issue by buncybunny** [ucbdrive/few-shot-object-detection#117]
![스크린샷, 2021-05-17 11-22-24](https://user-images.githubusercontent.com/57431963/118424452-4166b600-b702-11eb-9ac9-8616ee7a14d8.png)

I understand that config files with '_unfreeze' are "FRCN+ft_full".
But which one is 'TFA+fc' and 'TFA+cos'?

Can somebody please explain the differences amongst "faster_rcnn_R_101_FPN_ft_all_1shot.yaml" and
"faster_rcnn_R_101_FPN_ft_fc_all_1shot.yaml" and
"faster_rcnn_R_101_FPN_ft_novel_1shot.yaml"?

**Comment by g-lyc** [comment]
Hi，Did you find the solution?
