### ISSUE TITLE
_C.roi_align_forward raises a "RuntimeError: Not compiled with GPU support"

### ISSUE THREAD

**Issue by E-Galois** [ucbdrive/few-shot-object-detection#122]
I'm running the demo.py script, but from file "fsdet\layers\roi_align.py", the "_C.roi_align_forward" method raises a "RuntimeError: Not compiled with GPU support".
My pytorch is consistent with the cuda version 11.1 and I've already built fsdet with "python setup.py build develop". 

I tried to run demo in detectron2, but it does not raise such an error, and can finish inference.
What can be the cause?

**Comment by thomasehuang** [comment]
See [this](https://github.com/ucbdrive/few-shot-object-detection/issues/129). The detectron2 version we use is an old version (v0.2.1) and may not be compatible with higher CUDA versions. We plan on upgrading to the newest detectron2 version, but this may take some time.

**Comment by thomasehuang** [comment]
Just updated the installation instructions, you can try following it again. Will close this for now, but feel free to reopen it if it's still an issue for you.
