### ISSUE TITLE
training COCO on one GPU?

### ISSUE THREAD

**Issue by salehnia** [ucbdrive/few-shot-object-detection#124]
Hello, Can you share me your parameters for 1 GPU with 12 GB memory in training coco dataset?
I used of this Article(https://arxiv.org/abs/1706.02677) and set it as this:
gpu 8 -> 1
lr 0.02 -> 0.0025
max_iter 90000 ->720000

but i have this error now:
FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged

i had to choose lr very low as 0.00000125 and it will make different result. bAP is 0.0025 :(

**Comment by Wei-i** [comment]
I met the same problem, even if I have 8 GPU and the learning-rate is set as 0.02.
I also have `FloatingPointError`, I am so confused...
Do you fix this bug?

For training base classes using the default code in readme.md
```python
python3 -m tools.train_net --num-gpus 8 \
        --config-file configs/PascalVOC-detection/split1/faster_rcnn_R_101_base1.yaml

```

**Comment by Wei-i** [comment]
From this [issue](https://github.com/ucbdrive/few-shot-object-detection/issues/104), maybe I get it , my  latest version of detectron2 is 0.5, while the default is 0.2.

**Comment by alphacyp** [comment]
> 从这个[问题](https://github.com/ucbdrive/few-shot-object-detection/issues/104)，也许我明白了，我最新版本的detectron2是0.5，而默认是0.2。

Hello, sir! I have the same problem. Can you run normally after you change the version of detectron2?

**Comment by alphacyp** [comment]
> From this [issue](https://github.com/ucbdrive/few-shot-object-detection/issues/104), maybe I get it , my latest version of detectron2 is 0.5, while the default is 0.2.
Hello, sir! I have the same problem. Can you run normally after you change the version of detectron2?

**Comment by alphacyp** [comment]
> From this [issue](https://github.com/ucbdrive/few-shot-object-detection/issues/104), maybe I get it , my latest version of detectron2 is 0.5, while the default is 0.2.

Hello, sir! I have the same problem. Can you run normally after you change the version of detectron2?

**Comment by Wei-i** [comment]
> > From this [issue](https://github.com/ucbdrive/few-shot-object-detection/issues/104), maybe I get it , my latest version of detectron2 is 0.5, while the default is 0.2.
> 
> Hello, sir! I have the same problem. Can you run normally after you change the version of detectron2?

yes you can try

**Comment by salehnia** [comment]
Thank you @Wei-i , i changed detectron2 version to 0.2.1 and  parameters as i said in first message

**Comment by alphacyp** [comment]
> > > From this [issue](https://github.com/ucbdrive/few-shot-object-detection/issues/104), maybe I get it , my latest version of detectron2 is 0.5, while the default is 0.2.
> > 
> > 
> > Hello, sir! I have the same problem. Can you run normally after you change the version of detectron2?
> 
> yes you can try

Thank you very much for your reply. This problem has been solved for the time being.Is the version of detectron2 making the calculated AP value very low? Or,when the detectron2 version is 0.5, the trained model is normal, but the detectron2 version leads to errors in the AP test?Is that right?
Moreover,when I was performing Stage 2: Few-Shot Fine-Tuning,I can't find the fast_ rcnn_ R_ 101_ FPN_ ft_ novel1_ 1shot.yaml. do you have any solutions?

**Comment by Wei-i** [comment]
`fast_ rcnn_ R_ 101_ FPN_ ft_ novel1_ 1shot.yaml`  authors don't provide,  you can find it  in other issues.

**Comment by thomasehuang** [comment]
Thanks for the answers.

@alphacyp The exact reason is something we have to investigate, but we are planning on upgrading to the newest version of detectron2 (may take some time). The config file can be found in [this](https://github.com/ucbdrive/few-shot-object-detection/issues/13) issue. See my answer there.
