### ISSUE TITLE
About the test model's score threshold

### ISSUE THREAD

**Issue by RuoyuChen10** [ucbdrive/few-shot-object-detection#128]
Thanks for your work, when I try to test the model by the command:

```
python -m tools.test_net --num-gpus 1 --config-file configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_ft_all1_10shot.yaml --eval-all
```

I find that the threshold of the score when test is set as `0.05`

Indicate that `MODEL.ROI_HEADS.SCORE_THRESH_TEST=0.05`

There will be lots of boxes, in few-shot learning, how much proposal boxes is used each image?

Or, we only visualize the image set a high threshold?

Looking forward to your reply.

**Comment by RuoyuChen10** [comment]
> Thanks for your work, when I try to test the model by the command:
> 
> ```
> python -m tools.test_net --num-gpus 1 --config-file configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_ft_all1_10shot.yaml --eval-all
> ```
> 
> I find that the threshold of the score when test is set as `0.05`
> 
> Indicate that `MODEL.ROI_HEADS.SCORE_THRESH_TEST=0.05`
> 
> There will be lots of boxes, in few-shot learning, how much proposal boxes is used each image?
> 
> Or, we only visualize the image set a high threshold?
> 
> Looking forward to your reply.

I am sorry for my poor knowledge in object detection, I forget the proposals will enter into NMS operation to remove the extra box.

**Comment by thomasehuang** [comment]
Exactly! No need to apologize, we are all here to learn :)

You can check the [base config file](https://github.com/ucbdrive/few-shot-object-detection/blob/master/configs/Base-RCNN-FPN.yaml) for exact numbers regarding number of boxes if you're still curious.
