### ISSUE TITLE
FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged.

### ISSUE THREAD

**Issue by ElifErarslan1** [ucbdrive/few-shot-object-detection#131]
Hi, 
I have rearranged the code according to the custom dataset and when I ran the training code floating point error occurs. Although I changed the base learning rate, the issue still occurs.

**Comment by AISoltani** [comment]
> Hi,
> I have rearranged the code according to the custom dataset and when I ran the training code floating point error occurs. Although I changed the base learning rate, the issue still occurs.
what is your detectron2 version?

**Comment by AISoltani** [comment]
> Hi,
> I have rearranged the code according to the custom dataset and when I ran the training code floating point error occurs. Although I changed the base learning rate, the issue still occurs.

what is your detectron2 version?

**Comment by ElifErarslan1** [comment]
hi, I directly get it from instructions and its version is 0.4

**Comment by AISoltani** [comment]
> hi, I directly get it from instructions and its version is 0.4

downgrade to 0.3 or 0.2.1

**Comment by thomasehuang** [comment]
Thanks @AISoltani. At the time of release of this repository, we were using detectron2 v0.2.1. I will update the README to make it more clear, as it is quite outdated.

**Comment by ElifErarslan1** [comment]
Hi, 
I downgrade it to v0.3 and it worked. Thank you for your support.
