### ISSUE TITLE
seed cannot found in name

### ISSUE THREAD

**Issue by ElifErarslan1** [ucbdrive/few-shot-object-detection#133]
Hello again, 
When I try to fine-tune the last layer of the full model, seed cannot be found in the name hence program can't see dataset/vocsplit/seed folder, instead, it tries to find data in dataset/vocsplit folder hence it gives "No such file or directory" error. What can be the reason for the absence of seeds in the 'voc_2007_trainval_all1_1shot' split? 
Edit: when I look at the vocsplit folder that you mentioned in the data preparation part, there are additional .txt files outside of the seeds. What is the difference between these and in seeds? And, is it okay if I copy .txt files in one of the seeds to dataset/vocsplit folder?

**Comment by thomasehuang** [comment]
The `.txt` files outside the seed folders are for seed 0, or the first seed. These are used by previous works during evaluation. You should use these `.txt` files for fine-tuning the last layer of your model. The seeds are only used if you are interested in getting average performance across different runs.

**Comment by ElifErarslan1** [comment]
Thank you for your explanation.
