### ISSUE TITLE
Novel class label can't be seen in log files with multiple runs.

### ISSUE THREAD

**Issue by ElifErarslan1** [ucbdrive/few-shot-object-detection#138]
Hello,
When I try to fine-tune a custom dataset, novel ap reaches a maximum of 23.4% AP. However, when I run multiple experiments with run_experiments.py, I can't see the novel class label on the log screen, and nAP seems very high. But in config files for all classes, both novel and base classes are included. I am confused about if multiple runs take the novel class. And if it also takes the novel category why nAP is very high compared to fine-tuning? Can you please help me to solve this conflict?

**Comment by thomasehuang** [comment]
Running `run_experiments.py` actually trains models on the PASCAL VOC dataset by default. Did you modify the file to run experiments on your dataset? If not, that may explain why there's a difference in nAP.
