### ISSUE TITLE
Detecting Logos

### ISSUE THREAD

**Issue by AhmedHashish123** [ucbdrive/few-shot-object-detection#146]
Hello, this project is really great and easy to use. I was just wondering if there was a pretrained model in the available models that can detect logos, something like Apple's logo or any restaurant logo?

**Comment by AISoltani** [comment]
> Hello, this project is really great and easy to use. I was just wondering if there was a pretrained model in the available models that can detect logos, something like Apple's logo or any restaurant logo?

hey you, no!!! there is no any pretrained model to detect logos, you need to train this from the beginning.
