### ISSUE TITLE
LR schedule for the fine-tune phase

### ISSUE THREAD

**Issue by tonysy** [ucbdrive/few-shot-object-detection#16]
Hi,
I have noticed that you use different lr schedules in the fine-tune phase.
For the COCO experiments, when using 30 shots, the total iterations is up to 240000, which is larger than the base phase(110000).
I wonder does the iterations matter a lot for the fine-tune stage, 240000 iterations are too expensive for the fine-tuning.

**Comment by thomasehuang** [comment]
Hello,

The large number of fine-tuning iterations does not matter that much. For the 30 shot case, we observed the same level of performance using half as many (and potentially even fewer) iterations. I just evaluated the checkpoint at 48k iterations, and the model was able to achieve nAP 13.1 and nAP75 13.0. Also, we tried to make the learning schedule consistent with other experiments, so we did not tune the hyper parameters that much. A better learning schedule might require less fine-tuning iterations.

Hope that helps!
