### ISSUE TITLE
can't find faster_rcnn_R_101_FPN_ft_novel1_1shot.yaml 

### ISSUE THREAD

**Issue by uzair789** [ucbdrive/few-shot-object-detection#17]
I am trying to retrain the models following the tutorial here:
    https://github.com/ucbdrive/few-shot-object-detection/blob/master/TRAIN_INST.md#fine-tuning

I am trying to use the Novel weights instead of the random weights. When I run the following command:

    `python tools/train_net.py --num-gpus 8 \
        --config-file configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_ft_novel1_1shot.yaml \
        --opts MODEL.WEIGHTS checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_all1/model_reset_remove.pth

I see that the config file does not exist at that location. Also the --opts flag does not exist in the code base and Hence I am manually editing the yaml files for the coresponding weights file. 

WHere can I find the config files for the novel1_1shot setting?

**Comment by uzair789** [comment]
Duplicate

**Comment by pranay-ar** [comment]
> Duplicate

Hi @uzair789, how did you fix this issue? I am stuck with the same problem and I am unable to find the file anywhere. Looking forward to your reply. Thank you!
