### ISSUE TITLE
How to Register Novel Dataset ? 

### ISSUE THREAD

**Issue by raghavgurbaxani** [ucbdrive/few-shot-object-detection#19]
Hi 

I am trying to use my own dataset to fine tune the pipeline on, but it gives me the error of 'KeyError: "Dataset 'equipment_imgs' is not registered!' , how do I register this dataset to to fine tune the algorithm on this ?

**Comment by thomasehuang** [comment]
Hello,

You should register your dataset here first: [https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/data/datasets/builtin.py](https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/data/datasets/builtin.py).  Follow how the other datasets are registered to register your own dataset. Let us know if you have any questions about this.

Hope that helps!

**Comment by raghavgurbaxani** [comment]
@thomasehuang  thank you for your response 

I registered the dataset in the builtin.py 

```
_PREDEFINED_SPLITS_COCO["coco"] = {
    "coco_2014_train": ("coco/train2014", "coco/annotations/instances_train2014.json"),
    "custom": ("custom", "custom//custom_37_54_Pro.json"),
}
```

as follows 

but I get the error - 

```
 DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
  File "/home/Desktop/FSOD/few-shot-object-detection/fsdet/data/datasets/coco.py", line 65, in load_coco_json
    cat_ids = sorted(coco_api.getCatIds())
  File "/home/.local/lib/python3.6/site-packages/pycocotools/coco.py", line 170, in getCatIds
    cats = self.dataset['categories']
KeyError: 'categories'

```

Do you know where am I going wrong ? Is the way I am registering the dataset incorrect ?

**Comment by forhadsidhu** [comment]
@raghavgurbaxani do you solve the issue?

**Comment by xinw1012** [comment]
@raghavgurbaxani Were you using the COCO format for your novel annotations? It looks like the error comes from your new annotation file.  Hope it helps!

**Comment by xinw1012** [comment]
close the issue for now and feel free to reopen it if you have any other issues. Thanks!
