### ISSUE TITLE
error occurs "Dataset 'voc_2007_trainval_base1' is not registered!"

### ISSUE THREAD

**Issue by geonuk-kimmm** [ucbdrive/few-shot-object-detection#2]
Thanks for your interesting work. Unfortunately i found a error on training code like below.

` dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "py36/lib/python3.6/site-packages/detectron2/data/catalog.py", line 59, in get
    name, ", ".join(DatasetCatalog._REGISTERED.keys())
KeyError: "Dataset 'voc_2007_trainval_base1' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_minival_100, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2014_minival_100, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val"
`
Is there anything to do with your data setting?

**Comment by thomasehuang** [comment]
Thank you for your interest.

I tried installing the framework from scratch and running the training, and I did not run into this issue. Can you give me some more details about your setup? Do you have an existing Detectron2 installation? There might be a conflict between the two frameworks.

**Comment by thomasehuang** [comment]
I've just renamed `Detectron2` to `fsdet` to avoid conflict with existing `Detectron2` installations. Please try rebuilding the repository and seeing if it works.

To rebuild:
- Make sure you have the latest code
- Remove existing build files by running `rm -rf build/ **/*.so`
- Rebuild by running `python setup.py build develop`

**Comment by geonuk-kimmm** [comment]
I fixed the error. As you said, there was conflict with existing Detectron2. I built the codes with another conda env and it was successful. Thanks!

**Comment by 2006pmach** [comment]
Hi I run into the same error. I set up a fresh conda env with pytorch 1.7.1 and CUDA 10.1. I installed detectron2 using `python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.7/index.html`. But when I try to train the model `python -m tools.train_net --num-gpus 1 --config-file configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_base1.yaml` after copying the voc dataset and few shot files I get the same error as above. Somehow the few-shot datasets don't get registered it seems...

```csharp
Traceback (most recent call last):
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/data/catalog.py", line 51, in get
    f = self[name]
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/collections/__init__.py", line 991, in __getitem__
    raise KeyError(key)
KeyError: 'voc_2007_trainval_base1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/tools/train_net.py", line 169, in <module>
    args=(args,),
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/tools/train_net.py", line 151, in main
    trainer = Trainer(cfg)
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 381, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 541, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/config/config.py", line 192, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/config/config.py", line 229, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/data/build.py", line 316, in _train_loader_from_config
    proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/data/build.py", line 227, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/data/build.py", line 227, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/data/catalog.py", line 57, in get
    ) from e
KeyError: "Dataset 'voc_2007_trainval_base1' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_minival_100, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2014_minival_100, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_train_panoptic, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_panoptic, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, coco_2017_val_100_panoptic, lvis_v1_train, lvis_v1_val, lvis_v1_test_dev, lvis_v1_test_challenge, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, cityscapes_fine_panoptic_train, cityscapes_fine_panoptic_val, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, ade20k_sem_seg_train, ade20k_sem_seg_val"

```

**Comment by zzzzjx** [comment]
> Hi I run into the same error. I set up a fresh conda env with pytorch 1.7.1 and CUDA 10.1. I installed detectron2 using `python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.7/index.html`. But when I try to train the model `python -m tools.train_net --num-gpus 1 --config-file configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_base1.yaml` after copying the voc dataset and few shot files I get the same error as above. Somehow the few-shot datasets don't get registered it seems...
> 
> ```cs
> Traceback (most recent call last):
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/data/catalog.py", line 51, in get
>     f = self[name]
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/collections/__init__.py", line 991, in __getitem__
>     raise KeyError(key)
> KeyError: 'voc_2007_trainval_base1'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/tools/train_net.py", line 169, in <module>
>     args=(args,),
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/engine/launch.py", line 82, in launch
>     main_func(*args)
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/tools/train_net.py", line 151, in main
>     trainer = Trainer(cfg)
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 381, in __init__
>     data_loader = self.build_train_loader(cfg)
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 541, in build_train_loader
>     return build_detection_train_loader(cfg)
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/config/config.py", line 192, in wrapped
>     explicit_args = _get_args_from_config(from_config, *args, **kwargs)
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/config/config.py", line 229, in _get_args_from_config
>     ret = from_config_func(*args, **kwargs)
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/data/build.py", line 316, in _train_loader_from_config
>     proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/data/build.py", line 227, in get_detection_dataset_dicts
>     dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/data/build.py", line 227, in <listcomp>
>     dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
>   File "/scratch_net/clariden/chmayer/conda_envs/simpledet/lib/python3.6/site-packages/detectron2/data/catalog.py", line 57, in get
>     ) from e
> KeyError: "Dataset 'voc_2007_trainval_base1' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_minival_100, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2014_minival_100, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_train_panoptic, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_panoptic, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, coco_2017_val_100_panoptic, lvis_v1_train, lvis_v1_val, lvis_v1_test_dev, lvis_v1_test_challenge, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, cityscapes_fine_panoptic_train, cityscapes_fine_panoptic_val, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, ade20k_sem_seg_train, ade20k_sem_seg_val"
> ```
have you solved it ?

**Comment by 2006pmach** [comment]
@zzzzjx in case you are still looking for a solution. For me the problem was that I had detectron2 v0.5 installed with lacking support. So I uninstalled and forced to install v0.4 and now it works.

**Comment by Tongjiaxun** [comment]
> 

where is setup.py? I can not find it.
