### ISSUE TITLE
Basic few shot question

### ISSUE THREAD

**Issue by gaussiangit** [ucbdrive/few-shot-object-detection#20]
Lets say I have few images of particular class (different from COCO : base training set ? ). How can we use this to train for the new class  ?

**Comment by xinw1012** [comment]
In our two-stage training algorithm, we will first get a base model trained on the base classes and then reinitialize the last layers for the novel classes and fine-tune the new layers. For more details, you may refer to our paper here. https://arxiv.org/pdf/2003.06957.pdf  Thanks!
