### ISSUE TITLE
training procedure

### ISSUE THREAD

**Issue by lerndeep** [ucbdrive/few-shot-object-detection#21]
In your paper, you mention training two-stage but in your readme file just you provide base training. how can I train the network in two-stage?

**Comment by lerndeep** [comment]
could you please provide some idea about the defect and non-defect metal plate detection?

**Comment by MSiam** [comment]
https://github.com/ucbdrive/few-shot-object-detection/blob/master/TRAIN_INST.md

**Comment by xinw1012** [comment]
Close the issue for now and feel free to reopen it if you have any other questions.  Thanks!
