### ISSUE TITLE
Missing files for coco

### ISSUE THREAD

**Issue by Nadav1** [ucbdrive/few-shot-object-detection#23]
Hi, I couldn't find trainvalno5k.json and 5k.json - can you please point me where can I find them? 
Thanks.

**Comment by thomasehuang** [comment]
Hello,

See [https://github.com/ucbdrive/few-shot-object-detection/tree/master/datasets](https://github.com/ucbdrive/few-shot-object-detection/tree/master/datasets). They can be downloaded from [here](http://dl.yf.io/fs-det/datasets/cocosplit/datasplit/).

Hope that helps.
