### ISSUE TITLE
Combined Error

### ISSUE THREAD

**Issue by Ze-Yang** [ucbdrive/few-shot-object-detection#24]
When I try to initialize the weight for novel class and combine it to the base weights, it gives out en error as stated below:
RuntimeError: The expanded size of the tensor (21) must match the existing size (60) at non-singleton dimension 0.  Target sizes: [21, 1024].  Tensor sizes: [60, 1024]

Note that I use COCO dataset. Here's the commands I have run:
`python tools/ckpt_surgery.py
 --src1 checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_final.pth --method remove --save-dir checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_all
`

`python tools/train_net.py --num-gpus 8 
        --config-file configs/COCO-detection/faster_rcnn_R_101_FPN_ft_novel_10shot.yaml 
        MODEL.WEIGHTS checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_all/model_reset_remove.pth
`

`
python tools/ckpt_surgery.py
        --src1 checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_final.pth 
        --src2 checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_10shot/model_final.pth 
        --method combine 
        --save-dir checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_all
`
The error prompted out at the step of combine. Could you advise? Thanks.

**Comment by hashemijo** [comment]
I am also encountering this exact same error using the coco 1shot setup, and am very interested in resolving it. Thanks!

**Comment by Ze-Yang** [comment]
> I am also encountering this exact same error using the coco 1shot setup, and am very interested in resolving it. Thanks!

I have resolved it by adding '--coco' at the end of the command.

**Comment by hashemijo** [comment]
Thanks!
