### ISSUE TITLE
how to make vocsplit/box_{1,2,3,5,10}shot_{category}_train.txt?

### ISSUE THREAD

**Issue by pppplin** [ucbdrive/few-shot-object-detection#26]
Hi, 

Thanks for all your effort on this work, it is truly amazing! I'm trying to replicate the result for single run PASCAL VOC TFA w/ cos, what seed do you use in the report number (seed 30?)
More specifically,
vocsplit/
  box_{1,2,3,5,10}shot_{category}_train.txt → which seed is these files? 
  seed{1-29}/
    # shots)

Thanks!

**Comment by pppplin** [comment]
found the file

**Comment by amajee11us** [comment]
I am trying to do the same but am getting this error:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/vocsplit/box_10shot_aeroplane_train.txt'
It is not trying to look for a seed here? I only have one worker ie single GPU environment. Is it because of that?
