### ISSUE TITLE
About cumulative performance

### ISSUE THREAD

**Issue by HelloJianHan** [ucbdrive/few-shot-object-detection#28]
Hi, thx for you work. As you say, the average value across multiple runs is consistently lower than that on the first run, especially in the one-shot case. Is that means the few shot images in the first run used in FSRW are well selected which yeilds better performance than random selecting?

**Comment by thomasehuang** [comment]
Hello,

We don't really know the procedure the researchers used to select those shots, so I can't say. However, based on the results, we do see a much higher performance on the shots in the first run compared to the rest, so it could be true that the researchers selected shots that gave the best results.

Hope that helps.
