### ISSUE TITLE
Registering new dataset 

### ISSUE THREAD

**Issue by gaussiangit** [ucbdrive/few-shot-object-detection#29]
How can I register new dataset ? 
I have to create metadata for the new dataset under builtin ? 

https://github.com/ucbdrive/few-shot-object-detection/blob/a3c6a5e2e1b7d1dc31cc3f9df1016a67435e886c/fsdet/data/datasets/builtin.py#L16

**Comment by thomasehuang** [comment]
Hello,

You should register your dataset [here](https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/data/datasets/builtin.py) and add the metadata you need [here](https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/data/datasets/builtin_meta.py). For reading the dataset images and annotations, you can follow the format of the other datasets in [this](https://github.com/ucbdrive/few-shot-object-detection/tree/master/fsdet/data/datasets) directory. If your format is the same as the COCO annotations, you can probably just reuse their functions.

Hope that helps.

**Comment by amajee11us** [comment]
You can put the classes in each split "all", "base" and "novel" in builtin_meta.py and reference the name in builtin.py. Within builtin.py create a method for your dataset and create its implementation in fsdet/data/datasets directory. Hope it helps.
