### ISSUE TITLE
Adding a regression head

### ISSUE THREAD

**Issue by DecentMakeover** [ucbdrive/few-shot-object-detection#3]
Hi 

Thanks for sharing your work , along with the classification and regression head , i wanted to add another regression head. How can i go about this?

Thanks in advance.

**Comment by thomasehuang** [comment]
Hello, thank you for your interest. Your question actually allowed me to find a small issue in the repo that has now been fixed, so thanks for that.

See [https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/modeling/roi_heads/fast_rcnn.py#L322](https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/modeling/roi_heads/fast_rcnn.py#L322) for an example of adding output layers. You can create your own class and register it.

The output layers are used in [https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/modeling/roi_heads/roi_heads.py#L401-L405](https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/modeling/roi_heads/roi_heads.py#L401-L405). You can set the config parameter `cfg.MODEL.ROI_HEADS.OUTPUT_LAYER` to your new class name in your config file to use your defined class.

If you need to modify the logic for the entire head, you can again create your own class and register it, as shown in [https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/modeling/roi_heads/roi_heads.py#L357](https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/modeling/roi_heads/roi_heads.py#L357). The config parameter you need to set is `cfg.MODEL.ROI_HEADS.NAME`.

Hope that helps!

**Comment by DecentMakeover** [comment]
Thank you so much for your reply , i will check this out!
