### ISSUE TITLE
How can i evaluate the model without FPN?

### ISSUE THREAD

**Issue by geonuk-kimmm** [ucbdrive/few-shot-object-detection#30]
Thanks for nice work and source code.
I'd like to evaluate the model without FPN in backbone.

So, i changed config files 'Base-RCNN-FPN.yaml' as
VERSION: 2
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: **"build_resnet_backbone"**
  RPN:
    PRE_NMS_TOPK_TRAIN: 2000  
    PRE_NMS_TOPK_TEST: 1000  
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)

I changed backbone name and delete some descriptions for FPN feature level. 
And i didn't change source code. Is it enough to evaluate the model without FPN?

Thanks,

**Comment by thomasehuang** [comment]
That looks about right to me, as long as you change the backbone it should be correct. You can also take a look at the official Detectron2 config file [here](https://github.com/facebookresearch/detectron2/blob/master/configs/Base-RCNN-C4.yaml) for a model without FPN.
