### ISSUE TITLE
Questions about experimental results in Tab1 and Tab7

### ISSUE THREAD

**Issue by infrontofme** [ucbdrive/few-shot-object-detection#31]
Hi, thanks for sharing your work.
I well read your paper and found that there are 2 result on Pascal VOC.
Table 1 shows the amazing results on Pascal VOC, Is the mAP in Tab1 only on noval classes ?
Why the results in Table 1 and Table 7 are different ？

I am very confused about this，could you explained it?

thanks :)

**Comment by thomasehuang** [comment]
Hello, thank you for your interest.

Yes, Table 1 are results on the novel classes only. Table 7 has results on all the classes, and we also evaluate on multiple different random samples of the training shots. This allows us to also provide confidence intervals, which are useful for comparison.

Hope that helps!

**Comment by Wei-i** [comment]
@thomasehuang , hi, sorry to disturb you. I am confused that where the code refers to "95% confidence interval". Could you give me some advice(e.g. give me a link or file.py to the corresponding codes)?
I would be grateful if you could reply:)
