### ISSUE TITLE
How to get official results by Matlab API?

### ISSUE THREAD

**Issue by duynn912** [ucbdrive/few-shot-object-detection#33]
Dear authors,

The first question I wanna confirm that all results on your paper is from python evaluation or matlab. If this is from python, How do I can get this from Matlab. As far as, I know that some works provide a pickle of detection results (detections.pkl) to evaluate in official Matlab? Could you provide this file or any alternative for that?

The second one is that I successfully run your code, but when I checked the results I see inconsistently some locations. For examples, in table 1: the results in your table is different from the original papers at novel set 2 and 3
![image](https://user-images.githubusercontent.com/39177680/82874189-c724ab00-9f5f-11ea-81a1-91cef9559d71.png)
Besides, when I run your code:
python tools/train_net.py --num-gpus 1 \
        --config-file configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_ft_all1_1shot.yaml \
        --opts MODEL.WEIGHTS WEIGHTS_PATH
I get the results like this: 
![1shot](https://user-images.githubusercontent.com/39177680/82874615-69449300-9f60-11ea-815f-b93fba00bdaf.png)
I want to know whether it is true or not, because it is also different in your table 1. By the way, the result from base training I got like this one:
![1](https://user-images.githubusercontent.com/39177680/82874738-9a24c800-9f60-11ea-9505-aa10c561aeb0.png)

Hope to hear from you soon!
Sincerely,
Duynn

**Comment by thomasehuang** [comment]
Hello,

We do everything in python, including training and evaluation. We don't support Matlab evaluation, but we do save the predictions of the model during evaluation, which can be used to compute the performance in Matlab if you wanted.

Can you tell me which lines in table 1 are inconsistent? I checked the line you highlighted, but it looks fine to me.

Your results seem fine to me. The numbers won't be exactly the same, since there is still variance between runs. Some minor differences are expected.

Hope that helps!

**Comment by duynn912** [comment]
Hi @thomasehuang,

Thank you for your response!

Could you show me which file I can use to do evaluation for Matlab?

Relating to the inconsistent results, in original authors got results in novel 2 and 3 like this one: 
![image](https://user-images.githubusercontent.com/39177680/83215878-21a54d80-a192-11ea-9891-8b65b41cda87.png)
And I check the results in your paper as mentioned, it is a little different in 10-shot of novel 2, and all shots of novel 3?

**Comment by AmingWu** [comment]
@duynn912 , Do you reproduce the results in the paper? I obtain the similar results.
![QQ截图20200614185123](https://user-images.githubusercontent.com/38445175/84591342-1b8cbd80-ae70-11ea-94a7-ba642f273571.png)

**Comment by duynn912** [comment]
Hi @AmingWu,

As mentioned above, it is my results.

**Comment by AmingWu** [comment]
Hi, @duynn912 , do you reproduce the results of 3shot and 5shot?

**Comment by thomasehuang** [comment]
Hello @duynn912,

For the results for feature re-weighting, we referred to the numbers in the arxiv version of the paper, which has the latest numbers. The paper can be found [here](https://arxiv.org/pdf/1812.01866.pdf).

For the evaluation file, the detections from the model are saved to a file [here](https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/evaluation/coco_evaluation.py#L146). You can locate this file in the inference folder of your specified `OUTPUT_DIR` in the config. You should be able to write a Matlab script to do evaluation based on this file. You might have to add code to save the PASCAL VOC predictions, currently it doesn't save it.

Hope that helps!
