### ISSUE TITLE
cannot find config file faster_rcnn_R_101_FPN_ft_novel1_1shot.yaml

### ISSUE THREAD

**Issue by Ze-Yang** [ucbdrive/few-shot-object-detection#34]
The command line (below) you provide in TRAIN_INST.md indicates the need for faster_rcnn_R_101_FPN_ft_novel1_1shot.yaml, but I cannot find such file. Thanks.
```
python tools/train_net.py --num-gpus 8 \
        --config-file configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_ft_novel1_1shot.yaml \
        --opts MODEL.WEIGHTS checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_all1/model_reset_remove.pth
```

**Comment by duynn912** [comment]
Hi @Ze-Yang,

As I know, the author do not run this config but he provide like this:
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base1/model_reset_remove.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 5
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("voc_2007_trainval_novel1_1shot", )
  TEST: ('voc_2007_test_novel1',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (500, )
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel1_1shot"

Hope to help you!
Sincerely,

**Comment by thomasehuang** [comment]
Hello. As @duynn912 said, we don't actually use the novel initialization for VOC, so we didn't include those config files.

**Comment by ljjcoder** [comment]
@duynn912 @thomasehuang ，if I do not  use the novel initialization for VOC，how can I get the model_reset_combine.pth to run the final finetune step as below?
python3 -m tools.train_net --num-gpus 8 \
        --config-file configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_ft_all1_1shot.yaml \
        --opts MODEL.WEIGHTS WEIGHTS_PATH

**Comment by scott-vsi** [comment]
Their paper notes that for Pascal VOC, "simple random initialization can outperform initialization using fine-tuned novel weights" (Section 4.3). So instead, I believe, you create [random weights](https://github.com/ucbdrive/few-shot-object-detection/blob/master/docs/TRAIN_INST.md#random-weights): 

```python
python3 -m tools.ckpt_surgery \
        --src1 checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base1/model_final.pth \
        --method randinit \
        --save-dir checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_all1
```

which creates checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_all1/model_reset_surgery.pth. This is the file you provide as the `WEIGHTS_PATH` for the `--opts MODEL.WEIGHTS` flag


EDIT Just for reference, the config file @duynn912 posted was provided in #13
