### ISSUE TITLE
Freezing Layers for Finetuning

### ISSUE THREAD

**Issue by sehyungp92** [ucbdrive/few-shot-object-detection#39]
Firstly, many thanks for sharing your work.

I just had a very quick question on where I can find parts of the code that implements freezing of the layers and the cosine similarity classifier during the finetuning stage.

Kind regards,
Se

**Comment by amajee11us** [comment]
You can essentially pass it as a config 'cfg' and is picked up by the required module.
For this case there is an option to freeze the following: Backbone, proposal generator and ROI heads.
For Faster-RCNN have a look at : few-shot-object-detection/fsdet/modeling/meta_arch/rcnn.py lines- 42-56. In both these cases the requires grad param of the respective modules is set to FALSE.

**Comment by thomasehuang** [comment]
Thanks @amajee11us for answering the question!

The cosine similarity based classifier can be found [here](https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/modeling/roi_heads/fast_rcnn.py#L367).

Hope that helps!
