### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Fly-dream12** [ucbdrive/few-shot-object-detection#40]
I have successfully installed detectron2 and then i run python setup.py build develop to rebuild this repository, but I met this error :

/home/baby47/Documents/few-shot-object-detection-master/fsdet/layers/csrc/vision.cpp:79:8: error: ‘modulated_deform_conv_backward’ was not declared in this scope
       &modulated_deform_conv_backward,
        ^
/home/baby47/Documents/few-shot-object-detection-master/fsdet/layers/csrc/vision.cpp:79:8: note: suggested alternative:
In file included from /home/baby47/Documents/few-shot-object-detection-master/fsdet/layers/csrc/vision.cpp:7:0:
/home/baby47/Documents/few-shot-object-detection-master/fsdet/layers/csrc/deformable/deform_conv.h:314:13: note:   ‘detectron2::modulated_deform_conv_backward’
 inline void modulated_deform_conv_backward(
             ^
error: command 'gcc' failed with exit status 1

My environment is based on torch1.4.0 cuda10.0 and gcc 5.4.0.

Could you explain possible reasons?
Thanks

**Comment by anas-awadalla** [comment]
Having a similar issue as well.

**Comment by bahulkark** [comment]
Did you solve this issue?

**Comment by anas-awadalla** [comment]
Nope

**Comment by thomasehuang** [comment]
It is probably some compatibility issue, you can try searching the issue on the detectron2 repository [here](https://github.com/facebookresearch/detectron2). This [issue](https://github.com/facebookresearch/detectron2/issues/761) could be related. Let me know if it still isn't fixed.

**Comment by Fly-dream12** [comment]
I tried to rebuild it based on torch 1.6.0 and cuda 10.2, i still met this error, could you give any suggestions? @thomasehuang 
g++: error: FSCE-main/build/temp.linux-x86_64-3.6/../FSCE-main/fsdet/layers/csrc/vision.o: No such file or directory
and many other .o files are not found.
error: command 'g++' failed with exist status 1

**Comment by scott-vsi** [comment]
Are you using v0.1? If you are using master (or >=v0.2) there is nothing to compile.

**Comment by thomasehuang** [comment]
Installation instructions have been updated. It should work if you follow it now. Please reopen this issue or make a new issue if it still doesn't work for you.
