### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by bahulkark** [ucbdrive/few-shot-object-detection#41]
I am trying to implement the code but while running **setup.py,** I am getting this error. 

In file included from /content/few-shot-object-detection/fsdet/layers/csrc/vision.cpp:7:0:
/content/few-shot-object-detection/fsdet/layers/csrc/deformable/deform_conv.h:344:26: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
     AT_CHECK(offset.type().is_cuda(), "offset tensor is not on GPU!");
                          ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                 from /content/few-shot-object-detection/fsdet/layers/csrc/vision.cpp:3:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:262:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by anas-awadalla** [comment]
@bahulkark Did you manage to figure out the issue? I am running into the same problem.

**Comment by thomasehuang** [comment]
It is probably some compatibility issue, you can try searching the issue on the detectron2 repository [here](https://github.com/facebookresearch/detectron2).

For reference, I am using GCC 7.3, CUDA 10.0, and NVCC 10.0.
