### ISSUE TITLE
About data augmentation

### ISSUE THREAD

**Issue by xychen9459** [ucbdrive/few-shot-object-detection#42]
Hello. 

According to the configuration files, the minimum size of inputs (INPUT.MIN_SIZE_TRAIN) has multiple values. This setting means that multi-scale training is used in the experiment. I also reviewed the code from [Kang et al., 2019, Yan et al., 2019] and both of them use a single-scale training setting. I wonder whether the multi-scale training is one of the factors making your method have very significant improvement than currently meta-learning-based ones (some results have >10% improvement). Have you evaluated performance under the same experiment settings (such as single-scale training) in other methods?

Thanks.

**Comment by thomasehuang** [comment]
Yes, multi-scale training definitely contributed to the improvements we observed with our method, but we have not evaluated the exact numbers. That is a good suggestion, we will look into that. Thanks!
