### ISSUE TITLE
How to create a new shot for training, e.g. 20 shot or 30 shot?

### ISSUE THREAD

**Issue by duynn912** [ucbdrive/few-shot-object-detection#43]
Hi authors,

How can I add a new shot for training, e.g. 20 shot or 30 shot? I attempt to add 20 shot to train the network but your code just prints a string of keys of training dataset name like this:
![image](https://user-images.githubusercontent.com/39177680/85493960-0519fb00-b602-11ea-8dfd-3aa131ebadc0.png)

May you show me a way to register a new shot for training?

Sincerely,
Duynn

**Comment by thomasehuang** [comment]
Hello Duynn,

You have to register them as datasets in the [builtin.py](https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/data/datasets/builtin.py) file. If you're working with PASCAL VOC, you can add the numbers [here](https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/data/datasets/builtin.py#L176). It should be similar for the other datasets.

You also have to generate the data for the new shots. You can add the numbers [here](https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/prepare_voc_few_shot.py#L45) for PASCAL VOC and run the script.

Hope that helps!

**Comment by cats0212** [comment]
@duynn912 hi，i have the same question，Can you give me some advice？thanks

**Comment by xinw1012** [comment]
Please check Thomas’s suggestions in the thread and let us know if you have
additional questions. Thanks!
