### ISSUE TITLE
about training time.

### ISSUE THREAD

**Issue by dmuqlzhang** [ucbdrive/few-shot-object-detection#44]
thanks for your work,  about few shot, we expect less train data and less training time. but I think it use a lot of times during training steps,  maybe it Slow convergence compare meta learning method?

**Comment by thomasehuang** [comment]
We trained our models for many iterations since we observed continued improvements, but the performance reached a high value very quickly and then plateaued. A lower number of iterations would still probably work, though the performance would be lower.
