### ISSUE TITLE
Importerror: cannot import name '_C'

### ISSUE THREAD

**Issue by xTRam1** [ucbdrive/few-shot-object-detection#45]
I have done all the installations shown on README.mb but still, I get his error message whenever I try to do the demo.py:
Importerror: cannot import name '_C'

**Comment by thomasehuang** [comment]
There's an explanation for your issue [here](https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues). If that doesn't work, let me know.

**Comment by lukassoukup** [comment]
Hi, did that solution work for you? Thanks
