### ISSUE TITLE
AssertionError: Dataset 'voc_2007_trainval' is already registered! 

### ISSUE THREAD

**Issue by SpringUp** [ucbdrive/few-shot-object-detection#46]
how to slove this problem？

**Comment by thomasehuang** [comment]
Can you give me more information, such as the full error message? The code should run if you made no modifications, but I'm assuming you did.

**Comment by SpringUp** [comment]
Thank you for your reply. Yes, as you said, I modified the original code, but i have  solved this problem by clearing the previously registered files. Thank you again。

**Comment by qinzhengmei** [comment]
Hi
How do you unregister the dataset. @SpringUp
