### ISSUE TITLE
basic questions about trainval/test splits of VOC

### ISSUE THREAD

**Issue by squirrel16** [ucbdrive/few-shot-object-detection#5]
I wonder how to get the **base training list** in your **few-shot** setting and have some questions. Let's take VOC dataset example, the questions are:
1) For the **base training** which has abundant annotations of 15 base classes, will the training images include any object belong to the unlabeled 5 novel classes? (for example, the base *person* and the novel *sofa* are both in a single training image)
2) If the above 1. is true, how to handle the unlabeled novel classes during base training? (maybe not take it as background)
3) How can I get a filename list (like `trainval.txt`) for the **base training**? I only see the x-shot list for training in this URL:http://dl.yf.io/fs-det/datasets/vocsplit/

Thanks a lot.

**Comment by thomasehuang** [comment]
Hello, thank you for your interest.

1. The base training images could contain novel objects. We use all the images that contain base objects, regardless of whether there are any novel objects or not.
2. We don't do anything special to handle the novel objects during base training, so we treat it as background.
3. You should be able to find those files after downloading the official PASCAL dataset [here](http://host.robots.ox.ac.uk/pascal/VOC/index.html).

Hope that helps!
