### ISSUE TITLE
About detectron2 commit number

### ISSUE THREAD

**Issue by MARMOTatZJU** [ucbdrive/few-shot-object-detection#60]
Thanks for your release. 
Would you mind specify a _detectron2 (d2) commit number_ where you fork from Detectron2, so that we can better figure out the _fsdet_ part of code?
Thanks in advance!

**Comment by xinw1012** [comment]
We forked the initial release of Detectron2 (v0.1) which has been a while. We are working on upgrading the code now and removing the detectron2 dependencies. Stay tuned!

**Comment by xinw1012** [comment]
Feel free to reopen it later if you have more questions/comments.
