### ISSUE TITLE
Model combination error

### ISSUE THREAD

**Issue by AlexInWonderland** [ucbdrive/few-shot-object-detection#61]
Hi, 

We are facing an issue with respect to combining reweighed weights and base weight with the following errors. We modified some paths from the instruction because sometimes the mentioned files cannot be found (ex. configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_ft_novel1_1shot.yaml cannot be found so I modified it to configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_ft_all1_1shot.yaml ). Will this cause this issue? 

Traceback (most recent call last):
  File "tools/ckpt_surgery.py", line 250, in <module>
    combine_ckpts(args)
  File "tools/ckpt_surgery.py", line 126, in combine_ckpts
    surgery_loop(args, surgery)
  File "tools/ckpt_surgery.py", line 161, in surgery_loop
    surgery(param_name, True, tar_size, ckpt, ckpt2)
  File "tools/ckpt_surgery.py", line 120, in surgery
    new_weight[prev_cls:-1] = ckpt2_weight[:-1]
RuntimeError: The expanded size of the tensor (5) must match the existing size (20) at non-singleton dimension 0.  Target sizes: [5, 1024].  Tensor sizes: [20, 1024]

**Comment by AlexInWonderland** [comment]
the command I used is the following and dataset is pascal voc.

python tools/ckpt_surgery.py --src1 checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base1/model_final.pth --src2 checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel1_1shot/model_final.pth --method combine --save-dir checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_all1

**Comment by qinzhengmei** [comment]
Did you solve the problem? I have a similar mistake.
the command I used is the following and dataset is coco.

python3 -m tools.ckpt_surgery \
        --src1 checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_final.pth \
        --src2 checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_1shot/model_final.pth \
        --method combine \
        --save-dir checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_1shot_combine

**Comment by tailororrr** [comment]
I have a similar mistake.

**Comment by huhan233** [comment]
I have the same question.

**Comment by wbailer** [comment]
@qinzhengmei I had the same issue with COCO, make sure to add --coco to the arguments to get the right number of base/novel classes.

**Comment by thomasehuang** [comment]
Thanks for the answers. I will add a section in the README to make it more clear.
