### ISSUE TITLE
Did you use cosine classifier on base training as well as fine-tuning? 

### ISSUE THREAD

**Issue by geonuk-kimmm** [ucbdrive/few-shot-object-detection#64]
Hi there, 
Nice work and thanks for release your source code.
I wonder if you used cosine classifier on base training as well as fine-tuning, or FC layer is used in base training phase.

Thanks,

**Comment by xinw1012** [comment]
Hi, we provided results for both the cosine classifier as well as the FC layer.  We kept the layer choice (cosine/fc) consistent in the base training and fine-tuning.
