### ISSUE TITLE
I tried to run Demo.py on Windows, but“AssertionError: Checkpoint checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_1shot_combine/model_reset_combine.pth not found!”

### ISSUE THREAD

**Issue by hanhao2019102935** [ucbdrive/few-shot-object-detection#65]
I tried to run Demo.py on Windows, but“AssertionError: Checkpoint checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_1shot_combine/model_reset_combine.pth not found!”

**Comment by xinw1012** [comment]
Hi there,

you can refer to https://github.com/ucbdrive/few-shot-object-detection/blob/master/MODEL_ZOO.md for more details to download the pretrained checkpoints. 

Hope it helps!

**Comment by xinw1012** [comment]
Feel free to reopen it if there is still an issue.

**Comment by LDZ233** [comment]
I can't find the pretrained checkpoints，Could you tell me more details

**Comment by LDZ233** [comment]
> Hi there,
> 
> you can refer to https://github.com/ucbdrive/few-shot-object-detection/blob/master/MODEL_ZOO.md for more details to download the pretrained checkpoints.
> 
> Hope it helps!

Where can I find model_reset_combine.th? Could you tell me more details, thank you

**Comment by pranay-ar** [comment]
> > Hi there,
> > you can refer to https://github.com/ucbdrive/few-shot-object-detection/blob/master/MODEL_ZOO.md for more details to download the pretrained checkpoints.
> > Hope it helps!
> 
> Where can I find model_reset_combine.th? Could you tell me more details, thank you

Could you please let me know if you were able to find this file?
