### ISSUE TITLE
Pascal VOC splits

### ISSUE THREAD

**Issue by jshtok** [ucbdrive/few-shot-object-detection#66]
Hi,

Thank you for the great work. The three splits of Pascal VOC into 15 train - 5 test classes, are stated to be random; however, the algorithms are compared per split, and the results are not averaged over splits, so I guess the splits are determined. Can you please publish them explicitly, so that we could compare to the baselines correctly?

Thanks,
Joseph

**Comment by Ze-Yang** [comment]
I think it's equal to the splits in [feature reweighting](https://arxiv.org/abs/1812.01866).

**Comment by xinw1012** [comment]
Yes, we use the same splits as in feature reweighting as Ze-Yang pointed out. 

In this code repo, you can find the splits here. https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/data/datasets/builtin_meta.py or refer to https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/README.md for more details.

Hope it helps.

**Comment by jshtok** [comment]
Thank you very much!

**Comment by jgsimard** [comment]
Hi, I would like to know which split is associated with which seed in builtin_meta. Thanks!
