### ISSUE TITLE
Class agnostic box regression vs Class specific box regression

### ISSUE THREAD

**Issue by geonuk-kimmm** [ucbdrive/few-shot-object-detection#67]
Thanks for releasing the source code,
I found that you used class agnostic bbox regression layer.
Is there mAP comparison with bbox specific layer?

**Comment by xinw1012** [comment]
Hi, thanks for your interest in our work. 

Our work actually does not use a class agnostic box regression layer. It's based on the Faster R-CNN architecture. 

Let me know if I misunderstand your question.

**Comment by xinw1012** [comment]
Feel free to reopen it if there is still an issue.
