### ISSUE TITLE
lvis_v0.5_{train,val}.json

### ISSUE THREAD

**Issue by hjraad** [ucbdrive/few-shot-object-detection#69]
@thomasehuang @xinw1012 : Should we download this json file from LVIS webpage or we need to generate it? I have a hard time finding it.

**Comment by xinw1012** [comment]
We used to download the lvis_v0.5 labels from the LVIS website but it looks like the official website disabled the downloading the V0.5 labels.  I think the best way is to contact the LVIS authors or use their v1.0 labels directly.  We will try to obtain models with the latest labels in a short time.

**Comment by xinw1012** [comment]
Feel free to reopen it if there is still an issue.
