### ISSUE TITLE
custom dataset [suggestion]

### ISSUE THREAD

**Issue by hjamalirad** [ucbdrive/few-shot-object-detection#70]
@xinw1012 Adding a section on applying this to custom datasets, would make it more useful for a wider group of users. Have you thought about that? Would you be counting number of samples per class based on instances of a class or number of images? I assume the former, as most images even datasets like pascal voc or cityscapes would have multiple instances of different classes. Overall, I custom dataset mechanics, make this more generic.

**Comment by aeinsara** [comment]
> @xinw1012 Adding a section on applying this to custom datasets, would make it more useful for a wider group of users. Have you thought about that? Would you be counting number of samples per class based on instances of a class or number of images? I assume the former, as most images even datasets like pascal voc or cityscapes would have multiple instances of different classes. Overall, I custom dataset mechanics, make this more generic.

Did you solve this issue?

**Comment by pranay-ar** [comment]
@xinw1012 @aeinsara Were you able to implement this code on a custom dataset?

**Comment by thomasehuang** [comment]
See my answer in [this](https://github.com/ucbdrive/few-shot-object-detection/issues/130) issue for some instructions for now. That is a good suggestion and I can add it to a section in the README sometime.
