### ISSUE TITLE
model_reset_combine.pth

### ISSUE THREAD

**Issue by qinzhengmei** [ucbdrive/few-shot-object-detection#77]
I tried to run Demo.py on centOs, but“AssertionError: Checkpoint checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_1shot_combine/model_reset_combine.pth not found!”

**Comment by pranay-ar** [comment]
> I tried to run Demo.py on centOs, but“AssertionError: Checkpoint checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_1shot_combine/model_reset_combine.pth not found!”

Were you able to find this file? I am facing the same issue too?

**Comment by Vindhya-Singh** [comment]
Any update on how to mitigate this?

**Comment by pranay-ar** [comment]
> Any update on how to mitigate this?

I believe checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_1shot_combine/model_reset_combine.pth is an [intermediary file](https://github.com/ucbdrive/few-shot-object-detection/blob/master/docs/TRAIN_INST.md) (look at the last second step) in the training process. Are you sure you encountered this error while running the demo.py file? If it is some other file other than the model_reset_combine.pth, you could manually download them from the [model zoo](https://github.com/ucbdrive/few-shot-object-detection/blob/master/docs/MODEL_ZOO.md)
