### ISSUE TITLE
How to fix the parameters of model except the last two FC layers? 

### ISSUE THREAD

**Issue by HuangLian126** [ucbdrive/few-shot-object-detection#83]
I don not find codes about how to fix the parameters of model except the last two FC layers?

**Comment by tom-bu** [comment]
I don't think they do. In https://github.com/ucbdrive/few-shot-object-detection/blob/master/docs/TRAIN_INST.md, they just say that they combine the base weights from the base model with the novel weights by running 
```
python3 -m tools.ckpt_surgery \
        --src1 checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base1/model_final.pth \
        --src2 checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel1_1shot/model_final.pth \
        --method combine \
        --save-dir checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_all1
```

**Comment by HuangLian126** [comment]
All right, thanks for pointing that out.

**Comment by tom-bu** [comment]
Oh, I want to correct what I said. It appears that what I said above is for initializing with "Novel Weights" as opposed to "Random Weights." Fixing the parameters is done in the config file as seen in https://github.com/ucbdrive/few-shot-object-detection/blob/master/configs/COCO-detection/faster_rcnn_R_101_FPN_ft_all_10shot.yaml
```
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
```

**Comment by HuangLian126** [comment]
It is right !

**Comment by HeliosZhao** [comment]
They freeze the model layer here  https://github.com/ucbdrive/few-shot-object-detection/blob/6b0769b5d682fbf7fdcdaed0c1d0dfd51c373468/fsdet/modeling/meta_arch/rcnn.py#L53
