### ISSUE TITLE
where are  the xxx_base.txt files generated?

### ISSUE THREAD

**Issue by chengyu0910** [ucbdrive/few-shot-object-detection#84]
I just found the fewshot  txt files generated in prepare_xxx_few_shot.py.  where are  the xxx_base.txt files generated?

**Comment by lotuser1** [comment]
Have you solved this problem? I made this mistake when I started training ` "Dataset 'voc_2007_trainval_base1' is not registered!`

**Comment by thomasehuang** [comment]
The dataset files can be found [here](http://dl.yf.io/fs-det/datasets/). Regarding the `xx_base.txt` files, we only generate shots for each class, and in the code it will load in the correct class depending on whether it's a base class or a novel class.

Will close for now. Feel free to reopen if it is still an issue.
