### ISSUE TITLE
Train with other dataset in coco format

### ISSUE THREAD

**Issue by davesie** [ucbdrive/few-shot-object-detection#86]
Hey,
can you please guide me to the parts of the code I have to change in order to train the network with another data set?
I want to train it with the tt100k data set (https://cg.cs.tsinghua.edu.cn/traffic-sign/). I converted the annotations in COCO format already so it should be 'easy' I think if you know where to change the code.
I already changed up the config files and tried to register the new data set in builtin.py, but I'm not sure if that's all I have to do.
Would really appreciate help @xinw1012
Thanks!

**Comment by xinw1012** [comment]
Hey sorry for the delayed response.   Our codebase is built on detectron2 so basically, you could register new data following the instructions here.  https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html

I'm closing the issue and feel free to reopen it if you have additional questions.
