### ISSUE TITLE
Same model without FPN in backbone

### ISSUE THREAD

**Issue by geonuk-kimmm** [ucbdrive/few-shot-object-detection#9]
Hi,
I'm trying to test the proposed model without FPN in backbone.
so i changed config file like below (BASE-RCNN-FPN.yaml) 

MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_backbone"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2

It runs(base train) well with the config files but, I found there are some mismatch with checkpoint 

[04/07 11:49:55 fsdet.checkpoint.c2_model_loading]: Some model parameters are not in the checkpoint:
  proposal_generator.anchor_generator.cell_anchors.0
  proposal_generator.rpn_head.anchor_deltas.{bias, weight}
  proposal_generator.rpn_head.conv.{bias, weight}
  proposal_generator.rpn_head.objectness_logits.{bias, weight}
  roi_heads.box_head.fc1.{bias, weight}
  roi_heads.box_head.fc2.{bias, weight}
  roi_heads.box_predictor.bbox_pred.{bias, weight}
  roi_heads.box_predictor.cls_score.{bias, weight}
[04/07 11:49:55 fsdet.checkpoint.c2_model_loading]: The checkpoint contains parameters not used by the model:
  fc1000_b
  fc1000_w
  res5_0_branch2a_bn_beta
  res5_0_branch2a_bn_running_mean
  res5_0_branch2a_bn_running_var
  res5_0_branch2a_bn_gamma
  res5_0_branch2a_w
  res5_0_branch2b_bn_beta
  res5_0_branch2b_bn_running_mean
  res5_0_branch2b_bn_running_var
  res5_0_branch2b_bn_gamma
  res5_0_branch2b_w
  res5_0_branch2c_bn_beta
  res5_0_branch2c_bn_running_mean
  res5_0_branch2c_bn_running_var
  res5_0_branch2c_bn_gamma
  res5_0_branch2c_w
  res5_0_branch1_bn_beta
  res5_0_branch1_bn_running_mean
  res5_0_branch1_bn_running_var
  res5_0_branch1_bn_gamma
  res5_0_branch1_w
  res5_1_branch2a_bn_beta
  res5_1_branch2a_bn_running_mean
  res5_1_branch2a_bn_running_var
  res5_1_branch2a_bn_gamma
  res5_1_branch2a_w
  res5_1_branch2b_bn_beta
  res5_1_branch2b_bn_running_mean
  res5_1_branch2b_bn_running_var
  res5_1_branch2b_bn_gamma
  res5_1_branch2b_w
  res5_1_branch2c_bn_beta
  res5_1_branch2c_bn_running_mean
  res5_1_branch2c_bn_running_var
  res5_1_branch2c_bn_gamma
  res5_1_branch2c_w
  res5_2_branch2a_bn_beta
  res5_2_branch2a_bn_running_mean
  res5_2_branch2a_bn_running_var
  res5_2_branch2a_bn_gamma
  res5_2_branch2a_w
  res5_2_branch2b_bn_beta
  res5_2_branch2b_bn_running_mean
  res5_2_branch2b_bn_running_var
  res5_2_branch2b_bn_gamma
  res5_2_branch2b_w
  res5_2_branch2c_bn_beta
  res5_2_branch2c_bn_running_mean
  res5_2_branch2c_bn_running_var
  res5_2_branch2c_bn_gamma
  res5_2_branch2c_w

Is there anything to know when i try to change your config file?
Thanks!

**Comment by geonuk-kimmm** [comment]
With my config file, i could successfully train on base class. But at the phase i found some checkpoint mismatch as i noted.  The warning message occurs during model loading before iteration starts.

**Comment by thomasehuang** [comment]
I think you are loading the weights from a pre-trained ImageNet model, so you can ignore those messages. The parameters not in the checkpoint are ones you have to train, and the extra parameters can be ignored since they aren't used.

Hope that helps!
