### ISSUE TITLE
no model_reset_combine.pth

### ISSUE THREAD

**Issue by ljjcoder** [ucbdrive/few-shot-object-detection#99]
Hi,
Thank you for the great work！I have completed training on the base set using the following command：
python3 -m tools.train_net --num-gpus 8 \
        --config-file configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_base1.yaml 

When I was performing Stage 2: Few-Shot Fine-Tuning, I found that I could not generate the model_reset_combine.pth because we did not have the faster_rcnn_R_101_FPN_ft_novel1_1shot.yaml. I noticed that you did not perform fine-tune the predictor on the novel set by running on VOC, so I directly use model_reset_surgery.pth for fine-tune.

But I encountered the following problems:
![image](https://user-images.githubusercontent.com/40750189/111649646-8627bb00-883f-11eb-9928-d7706136ff54.png)
Can you give me some suggestions to fix this error？

**Comment by cats0212** [comment]
i also have this question。do you solve it？thanks

**Comment by pranay-ar** [comment]
> i also have this question。do you solve it？thanks

I have the same question too, were you able to find this file?

**Comment by YounkHo** [comment]
I also have this problem too. Have you found the faster_rcnn_R_101_FPN_ft_novel1_1shot.yaml files?

**Comment by thomasehuang** [comment]
Apologies for the confusion in the previous version of the instructions. The training instructions have been updated, so it should be more clear now. Will close the issue for now, please reopen if it is still an issue.
